language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script:
  - git clone https://github.com/squizlabs/PHP_CodeSniffer.git phpcs
  - git clone https://github.com/magento-ecg/coding-standard.git magento_coding_standard
  - phpcs/scripts/phpcs --config-set installed_paths magento_coding_standard
  - phpcs/scripts/phpcs --ignore=phpcs,magento_coding_standard --standard=EcgM2 .
